//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSample.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 id,name,hd,bab,skill_points
        ///1,Cleric,6,0.6,4
        ///2,Fighter,10,1,2
        ///3,Wizard,4,0.4,6
        ///4,Ranger,8,1,6
        ///5,Barbarian,12,1,2
        ///6,Monk,8,1,4 的本地化字符串。
        /// </summary>
        internal static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id,type,params
        ///1,1, 
        ///2,2,  的本地化字符串。
        /// </summary>
        internal static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id,scene_type,room_list,default_room_id
        ///1,1,1,1
        ///2,2,2,2
        ///3,3,, 的本地化字符串。
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 race_id,fname,lname
        ///1,David,Finci
        ///1,Tim,Johnson
        ///1,Stone,Blightblade
        ///2,Flint,Fireforge
        ///2,Dwarnin,Ironfist
        ///2,Redd,Ironhammer
        ///3,Ancentril,Sorrowoods
        ///3,Tanis,Moonlight
        ///3,Ivrin,Eveningstar 的本地化字符串。
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id,name,type
        ///1,Tim Klan,1 的本地化字符串。
        /// </summary>
        internal static string objects {
            get {
                return ResourceManager.GetString("objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id,type,name,str_m,int_m,dex_m,con_m,wis_m,cha_m
        ///1,1,Human,0,0,0,0,0,0
        ///2,1,Dwarf,2,0,0,2,0,-2
        ///3,1,Elf,0,0,2,-2,0,0
        ///101,2,Goblin,-2,-2,2,-2,2,-2
        ///102,2,Bugbear,2,-2,-2,2,0,-2
        ///103,2,Wolf,-2,-2,2,-2,2,-2 的本地化字符串。
        /// </summary>
        internal static string race {
            get {
                return ResourceManager.GetString("race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id,desc,directions,objects,special_commands
        ///1,,0,,Fixed
        ///2,,0,,Fixed
        ///3,Test Desc,2,1,
        ///99,,0,,New:N:1:0|Load:L:2:0 的本地化字符串。
        /// </summary>
        internal static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
    }
}
